OpenAI:
  api_key: null
  base_url: https://api.openai.com/v1
  ai_model: gpt-4.1-mini
  local_transcription_model_file: base
  response_lang: English
  audio_lang: English
  response_request_timeout_seconds: 10
  summarize_request_timeout_seconds: 30
  temperature: 0.0
Deepgram:
  api_key: API_KEY
Together:
  api_key: API_KEY
  ai_model: mistralai/Mixtral-8x7B-Instruct-v0.1
  base_url: https://api.together.xyz
WhisperCpp:
  local_transcription_model_file: base
General:
  voice_filter_enabled: true
  voice_filter_profile: my_voice.npy
  voice_filter_threshold: 0.625
  inverted_voice_response: true
  voice_identification_enabled: false
  log_file: logs/Transcribe.log
  save_llm_response_to_file: true
  llm_response_file: logs/response.txt
  transcript_audio_duration_seconds: 5
  clear_transcript_periodically: false
  clear_transcript_interval_seconds: 90
  use_api: false
  mic_device_index: -1
  speaker_device_index: -1
  disable_mic: false
  disable_speaker: false
  stt: whisper
  continuous_response: true
  continuous_read: true
  llm_response_interval: 10
  tts_speech_rate: 1.3
  tts_playback_volume: 0.5
  chat_inference_provider: openai
  default_prompt_preamble: 'You are a casual pal, genuinely interested in the conversation
    at hand. A poor transcription of conversation is given below. '
  default_prompt_epilogue: Please respond, in detail, to the conversation. Confidently
    give a straightforward response to the speaker, even if you don't understand them.
    Give your response in square brackets. DO NOT ask to repeat, and DO NOT ask for
    clarification. Just answer the speaker directly.
  system_prompt: "\u201CYou are IT expert.  Read the entire conversation history provided\
    \ and then give a single, clear recommendation, output crisp line (5-12 words)\
    \ for me to say.\""
  summary_prompt: "create a summary of the following text, highlight key points. \
    \ Also answer any questions asked by the colleague directly or indirectly based\
    \ on the whole conversation. Then provide suggestions and questions for discussions\
    \ that I can use. Keep them concise\u2014one sentence or even a few keywords.\
    \ Keep all suggestions short and clear."
  initial_convo:
    first:
      role: You
      content: Hey assistant,  you have deep IT expertise. As you listen to the discussion
        - Generate short, direct response option that I can say offering your expert
        insight or suggestion. Then, in a separate paragraph, add extra context, clarifications,
        or follow-up questions that might help me dive deeper into the topic if needed,
        including any additional information, definitions, or explanations on tools
        or concepts so I have sufficient background. This should also be short, direct
        response.
    second:
      role: assistant
      content: Hello, V. You are awesome. I am doing very well and looking forward
        to some light hearted banter with you.
